{{- if .Values.consulAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-consul-agent-config"
  labels:
    app: "{{ template "vault.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  extra-from-values.json: |
{{ tpl .Values.consulAgent.extraConfig . | indent 4 }}
{{- end }}