apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "atlassian-confluence.fullname" . }}
  labels:
    app: {{ template "atlassian-confluence.name" . }}
    chart: {{ template "atlassian-confluence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "atlassian-confluence.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "atlassian-confluence.name" . }}
        release: {{ .Release.Name }}
    spec:
      #initContainers:
      #  - name: chown-data-volume
      #    image: busybox
      #    imagePullPolicy: {{ .Values.image.pullPolicy }}
      #    command: ["chown", "2:2", "-R", "/var/atlassian/confluence"]
      #    volumeMounts:
      #    - name: data
      #      mountPath: /var/atlassian/confluence
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #securityContext:
          #  runAsUser: 0
          #  allowPrivilegeEscalation: true
          env:
            - name: X_PROXY_NAME
              value: {{ .Values.confluence.reverseProxyHost | quote }}
            - name: X_PROXY_PORT
              value: {{ .Values.confluence.reverseProxyPort | quote }}
            - name: X_PROXY_SCHEME
              value: {{ .Values.confluence.reverseProxyScheme | quote }}
            - name: JAVA_OPTS
              value: {{ printf "-Xmx%s -Xms%s %s %s -Dsynchrony.memory.max=%s" .Values.confluence.javaMaxHeapSize .Values.confluence.javaHeapSize .Values.confluence.javaMemoryOptions .Values.confluence.javaOptions .Values.synchrony.javaHeapSize| quote }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - name: synchrony
              containerPort: 8091
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          #volumeMounts:
          #  - mountPath: /var/atlassian/confluence/analytics-logs
          #    name: data
          #    subPath: analytics-logs
          #  - mountPath: /var/atlassian/confluence/confluence.cfg.xml
          #    name: data
          #    subPath: confluence.cfg.xml
          #  - mountPath: /var/atlassian/confluence/attachments
          #    name: data
          #    subPath: attachments
          #  - mountPath: /var/atlassian/confluence/backups
          #    name: data
          #    subPath: backups
          #  - mountPath: /var/atlassian/confluence/bundled-plugins
          #    name: data
          #    subPath: bundled-plugins
          #  - mountPath: /var/atlassian/confluence/imgEffects
          #    name: data
          #    subPath: imgEffects
          #  - mountPath: /var/atlassian/confluence/journal
          #    name: data
          #    subPath: journal
          #  - mountPath: /var/atlassian/confluence/logs
          #    name: data
          #    subPath: logs
          #  - mountPath: /var/atlassian/confluence/plugins-cache
          #    name: data
          #    subPath: plugins-cache
          #  - mountPath: /var/atlassian/confluence/plugins-osgi-cache/framework-bundles
          #    name: data
          #    subPath: plugins-osgi-cache/framework-bundles
          #  - mountPath: /var/atlassian/confluence/plugins-osgi-cache/transformed-plugins
          #    name: data
          #    subPath: plugins-osgi-cache/transformed-plugins
          #  - mountPath: /var/atlassian/confluence/plugins-temp
          #    name: data
          #    subPath: plugins-temp
          #  - mountPath: /var/atlassian/confluence/shared-home
          #    name: data
          #    subPath: shared-home
          #  - mountPath: /var/atlassian/confluence/temp
          #    name: data
          #    subPath: temp
          #  - mountPath: /var/atlassian/confluence/viewfile
          #    name: data
          #    subPath: viewfile
          #  - mountPath: /var/atlassian/confluence/webresource-temp
          #    name: data
          #    subPath: webresource-temp
              #/var/atlassian/application-data/confluence
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "atlassian-confluence.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
