{
 "title": "Kubernetes Control Plane Status",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Control Plane UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100",
     "legendFormat": "Scheduler Server Up"
    },
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100",
     "legendFormat": "Controller Manager Up"
    },
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / sum(up{job=\"apiserver\"})) * 100",
     "legendFormat": "API Server Up"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / sum(up{job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[5m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.9, sum by (le,verb) (rate(apiserver_request_latencies_bucket[5m]))) / 1e+06) >= 0"
    }
   ]
  },
  {
   "title": "End to End Scheduling Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(scheduler_e2e_scheduling_latency_microseconds_bucket{job=\"kube-scheduler\"}) by (le,cluster))",
     "legendFormat": "quantile-0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(scheduler_e2e_scheduling_latency_microseconds_bucket{job=\"kube-scheduler\"}) by (le,cluster))",
     "legendFormat": "quantile-0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(scheduler_e2e_scheduling_latency_microseconds_bucket{job=\"kube-scheduler\"}) by (le,cluster))",
     "legendFormat": "quantile-0.99"
    }
   ]
  }
 ]
}