{
 "title": "K8s Node Master",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Node Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Node Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Node CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_size{nodename=~\"$node\"}) - sum (node_filesystem_free{nodename=~\"$node\"})) / sum (node_filesystem_size{nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_size{nodename=~\"$node\"}) - sum (node_filesystem_free{nodename=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Total Node Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (node_filesystem_size{nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((avg(irate(node_cpu{nodename=~\"$node\", mode=\"system\"}[5m])) * 100))",
     "legendFormat": "system"
    },
    {
     "expr": "sum((avg(irate(node_cpu{nodename=~\"$node\", mode=\"user\"}[5m])) * 100))",
     "legendFormat": "user"
    },
    {
     "expr": "sum((avg(irate(node_cpu{nodename=~\"$node\", mode=\"iowait\"}[5m])) * 100))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum((avg(irate(node_cpu{nodename=~\"$node\", mode=\"steal\"}[5m])) * 100))",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable{nodename=~\"$node\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(node_memory_MemFree{nodename=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_memory_Active{nodename=~\"$node\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Load per Node",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_load1{nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_load1{nodename=~\"$node\"}) / count(node_cpu{mode=\"system\",nodename=~\"$node\"}) "
    }
   ]
  },
  {
   "title": "Disk Usage and Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free{nodename=~\"$node\"}) by (nodename)",
     "legendFormat": "{{ nodename }} free"
    },
    {
     "expr": "(sum(node_filesystem_size{nodename=~\"$node\"}) by (nodename) - sum(node_filesystem_free) by (nodename))",
     "legendFormat": "{{ nodename }} usage"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read{nodename=~\"$node\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written{nodename=~\"$node\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed{nodename=~\"$node\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed{nodename=~\"$node\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{nodename=~\"$node\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes{nodename=~\"$node\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_network_receive_errs{nodename=~\"$node\"})",
     "legendFormat": "in"
    },
    {
     "expr": "sum(node_network_transmit_errs{nodename=~\"$node\"})",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets{nodename=~\"$node\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets{nodename=~\"$node\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}