{
 "title": "Cluster Node Server Details",
 "description": "Dashboard to get an overview of one server",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "load 1m {{ instance }}"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "load 5m {{ instance }}"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "load 15m {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"} - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory used {{ instance }}"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$server\"}",
     "legendFormat": "memory buffers {{ instance }}"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$server\"}",
     "legendFormat": "memory cached {{ instance }}"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$server\"}",
     "legendFormat": "memory free {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemFree{instance=~\"$server\"}  - node_memory_Buffers{instance=~\"$server\"} - node_memory_Cached{instance=~\"$server\"})) /node_memory_MemTotal{instance=~\"$server\"}) * 100\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=~\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=~\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",instance=~\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",instance=~\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}