{
 "title": "K8s Deployments Master",
 "description": "Deployment overview for Kubernetes deploys.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Up-to-date",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max(kube_deployment_status_observed_generation{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max(kube_deployment_metadata_generation{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(max(kube_deployment_status_replicas{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "current replicas"
    },
    {
     "expr": "sum(min(kube_deployment_status_replicas_available{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "available"
    },
    {
     "expr": "sum(max(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(min(kube_deployment_status_replicas_updated{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(max(kube_deployment_spec_replicas{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Updated Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=~\"$deployment\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Generations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation{deployment=~\"$deployment\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}