{
 "title": "K8s Statefulsets Master",
 "description": "Deployment overview for Kubernetes deploys.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "statefulset",
    "label": "Statefulset",
    "query": "label_values(kube_statefulset_metadata_generation{namespace=~\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Statefulset Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{statefulset=~\"$statefulset\"}) "
    }
   ]
  },
  {
   "title": "Statefulset Replicas - Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{statefulset=~\"$statefulset\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_observed_generation{statefulset=~\"$statefulset\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_metadata_generation{statefulset=~\"$statefulset\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(max(kube_statefulset_status_replicas{statefulset=~\"$statefulset\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "available"
    },
    {
     "expr": "sum(max(kube_statefulset_replicas{statefulset=~\"$statefulset\",namespace=~\"$namespace\"}) without (instance, pod))",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=~\"$statefulset\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=~\"$statefulset\",namespace=~\"$namespace\"}) without (instance, pod)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Generations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_observed_generation{statefulset=~\"$statefulset\"}",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  }
 ]
}