{
 "title": "K8s Container Master",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum(container_memory_usage_bytes{pod_name=~\"$pod\"}) by (pod_name))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$pod\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\"}[2m])) by (pod_name))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound) Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m]))"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound) Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m]))"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Write IOPS Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "format": "wps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_fs_write_seconds_total{pod_name=~\"$pod\"}[2m]))"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_write_seconds_total{pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Read IOPS Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "format": "rps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_fs_io_time_seconds_total{pod_name=~\"$pod\"}[2m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}