{{- if (not .Values.isGrafanaIstio) -}}
{{- if and .Values.rbac.create (not .Values.rbac.namespaced) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "grafana.fullname" . }}-clusterrolebinding
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "grafana.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "grafana.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}