apiVersion: v1
kind: ServiceAccount
{{- if .Values.kialiOperator.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.kialiOperator.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: kiali-operator-sa
  labels:
    app: {{ template "kiali-operator.name" . }}
    chart: {{ template "kiali-operator.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    version: {{ .Values.kialiOperator.version }}