
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx.fullname" . }}-config
  labels:
    app: {{ template "nginx.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  {{- if .Values.nginx.conf }}
  nginx.conf: |
{{ .Values.nginx.conf | indent 4}}
  {{- end }}
   {{- if .Values.nginx.virtualhost.conf }}
  virtualhost.conf: |
{{ .Values.nginx.virtualhost.conf | indent 4}}
  {{- end }}
