apiVersion: v1
kind: Service
metadata:
  name: {{ template "smtp.fullname" . }}
  labels:
    app: {{ template "smtp.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
{{- if ne .Values.service.type "ClusterIP" }}
      targetPort: {{ .Values.service.internalPort }}
{{- end }}
      protocol: TCP
      name: {{ template "smtp.fullname" . }}
  selector:
    app: {{ template "smtp.fullname" . }}
    release: {{ .Release.Name }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  loadBalancerSourceRanges: {{.Values.service.loadBalancerSourceRanges}}
  {{- if .Values.service.loadBalancerIP}}
  loadBalancerIP: {{.Values.service.loadBalancerIP}}
  {{- end }}
  {{- end }}
